version: "3.7"
services:
  web:
    container_name: webserver
    image: nginx:1.22.1-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www/html/backend
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend
    tty: true
    networks:
      - app

  frontend:
    image: antoniopapa1991/admin-frontend
    depends_on:
      - backend
    networks:
      - app

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: laravel-admin
      DB_USERNAME: root
      DB_PASSWORD: admin
    ports:
      - ":9000"
    env_file: .env
    tty: true
    volumes:
      - .:/var/www/html/backend
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: admin_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_admin
      MYSQL_USER: arifin
      MYSQL_PASSWORD: arifin
    volumes:
      - ./data-mysql:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app

networks:
  app:
    driver: bridge
