version: "3.7"
services:
  # frontend:
  #   image: antoniopapa1991/admin-frontend
  #   depends_on:
  #     - backend
  #   networks:
  #     - app

  backend:
    container_name: admin-backend
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: laravel-admin
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: admin_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: laravel-admin
      MYSQL_USER: arifin
      MYSQL_PASSWORD: arifin
    volumes:
      - .data-mysql:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app

networks:
  app:
